package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	doc := &model.CategoryDoc{Name: input.Name}
	if err := r.CategoryRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphCategory(doc), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategory) (*model.Category, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Name != nil {
		set["name"] = *input.Name
	}

	doc, err := r.CategoryRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("category not found")
	}
	return toGraphCategory(doc), nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.CategoryRepo.Delete(ctx, oid)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	docs, err := r.CategoryRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Category, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphCategory(d))
	}
	return out, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.CategoryRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphCategory(doc), nil
}
