package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.NewCustomer) (*model.Customer, error) {
	doc := &model.CustomerDoc{
		Name:    input.Name,
		Phone:   input.Phone,
		Address: input.Address,
	}
	if err := r.CustomerRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphCustomer(doc), nil
}

// UpdateCustomer is the resolver for the updateCustomer field.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id string, input model.UpdateCustomer) (*model.Customer, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Name != nil {
		set["name"] = *input.Name
	}
	if input.Phone != nil {
		set["phone"] = *input.Phone
	}
	if input.Address != nil {
		set["address"] = *input.Address
	}
	if input.Status != nil {
		set["status"] = *input.Status
	}

	doc, err := r.CustomerRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("customer not found")
	}
	return toGraphCustomer(doc), nil
}

// DeleteCustomer is the resolver for the deleteCustomer field.
func (r *mutationResolver) DeleteCustomer(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.CustomerRepo.Delete(ctx, oid)
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	docs, err := r.CustomerRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Customer, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphCustomer(d))
	}
	return out, nil
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.CustomerRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphCustomer(doc), nil
}
