package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateDamagedProduct is the resolver for the createDamagedProduct field.
func (r *mutationResolver) CreateDamagedProduct(ctx context.Context, input model.NewDamagedProduct) (*model.DamagedProduct, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	userID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	productID, err := bson.ObjectIDFromHex(input.ProductID)
	if err != nil {
		return nil, fmt.Errorf("invalid productId: %w", err)
	}

	product, err := r.ProductRepo.FindByID(ctx, productID)
	if err != nil {
		return nil, err
	}
	if product == nil {
		return nil, errors.New("product not found")
	}
	if input.Quantity <= 0 {
		return nil, errors.New("quantity must be greater than zero")
	}
	if input.Quantity > product.StockQty {
		return nil, fmt.Errorf("insufficient stock for %s: have %.2f, requested %.2f", product.Name, product.StockQty, input.Quantity)
	}

	doc := &model.DamagedProductDoc{
		ProductID: productID,
		UserID:    userID,
		Quantity:  input.Quantity,
		CostPrice: product.CostPrice,
		Reason:    input.Reason,
		Note:      input.Note,
		Date:      time.Now().Unix(),
	}
	if err := r.DamagedProductRepo.Create(ctx, doc); err != nil {
		return nil, err
	}

	if err := r.ProductRepo.AdjustStock(ctx, productID, -input.Quantity, nil); err != nil {
		return nil, err
	}

	return toGraphDamagedProduct(doc), nil
}

// DeleteDamagedProduct is the resolver for the deleteDamagedProduct field.
func (r *mutationResolver) DeleteDamagedProduct(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}

	doc, err := r.DamagedProductRepo.FindByID(ctx, oid)
	if err != nil {
		return false, err
	}
	if doc == nil {
		return false, nil
	}

	if err := r.ProductRepo.AdjustStock(ctx, doc.ProductID, doc.Quantity, nil); err != nil {
		return false, err
	}

	return r.DamagedProductRepo.Delete(ctx, oid)
}

// DamagedProducts is the resolver for the damagedProducts field.
func (r *queryResolver) DamagedProducts(ctx context.Context) ([]*model.DamagedProduct, error) {
	docs, err := r.DamagedProductRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.DamagedProduct, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphDamagedProduct(d))
	}
	return out, nil
}

// DamagedProduct is the resolver for the damagedProduct field.
func (r *queryResolver) DamagedProduct(ctx context.Context, id string) (*model.DamagedProduct, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.DamagedProductRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphDamagedProduct(doc), nil
}

// DamagedProductsByProduct is the resolver for the damagedProductsByProduct field.
func (r *queryResolver) DamagedProductsByProduct(ctx context.Context, productID string) ([]*model.DamagedProduct, error) {
	oid, err := bson.ObjectIDFromHex(productID)
	if err != nil {
		return nil, fmt.Errorf("invalid productId: %w", err)
	}

	docs, err := r.DamagedProductRepo.FindByProduct(ctx, oid)
	if err != nil {
		return nil, err
	}

	out := make([]*model.DamagedProduct, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphDamagedProduct(d))
	}
	return out, nil
}
