package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateDebtPayment is the resolver for the createDebtPayment field.
func (r *mutationResolver) CreateDebtPayment(ctx context.Context, input model.NewDebtPayment) (*model.DebtPayment, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	userID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	saleID, err := bson.ObjectIDFromHex(input.SaleID)
	if err != nil {
		return nil, fmt.Errorf("invalid saleId: %w", err)
	}

	if input.AmountPaid <= 0 {
		return nil, errors.New("amountPaid must be greater than zero")
	}

	sale, applied, err := r.SaleRepo.ApplyPayment(ctx, saleID, input.AmountPaid)
	if err != nil {
		return nil, err
	}
	if sale == nil {
		return nil, errors.New("sale not found")
	}
	if sale.CustomerID == nil {
		return nil, errors.New("sale has no associated customer")
	}
	if applied <= 0 {
		return nil, errors.New("this invoice has no remaining debt")
	}

	if err := r.CustomerRepo.AdjustDebt(ctx, *sale.CustomerID, -applied); err != nil {
		return nil, err
	}

	doc := &model.DebtPaymentDoc{
		SaleID:      saleID,
		CustomerID:  *sale.CustomerID,
		UserID:      userID,
		AmountPaid:  applied,
		PaymentDate: time.Now().Unix(),
		Note:        input.Note,
	}
	if err := r.DebtPaymentRepo.Create(ctx, doc); err != nil {
		return nil, err
	}

	return toGraphDebtPayment(doc), nil
}

// DebtPayments is the resolver for the debtPayments field.
func (r *queryResolver) DebtPayments(ctx context.Context) ([]*model.DebtPayment, error) {
	docs, err := r.DebtPaymentRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.DebtPayment, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphDebtPayment(d))
	}
	return out, nil
}

// DebtPaymentsBySale is the resolver for the debtPaymentsBySale field.
func (r *queryResolver) DebtPaymentsBySale(ctx context.Context, saleID string) ([]*model.DebtPayment, error) {
	oid, err := bson.ObjectIDFromHex(saleID)
	if err != nil {
		return nil, fmt.Errorf("invalid saleId: %w", err)
	}

	docs, err := r.DebtPaymentRepo.FindBySale(ctx, oid)
	if err != nil {
		return nil, err
	}

	out := make([]*model.DebtPayment, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphDebtPayment(d))
	}
	return out, nil
}

// DebtPaymentsByCustomer is the resolver for the debtPaymentsByCustomer field.
func (r *queryResolver) DebtPaymentsByCustomer(ctx context.Context, customerID string) ([]*model.DebtPayment, error) {
	oid, err := bson.ObjectIDFromHex(customerID)
	if err != nil {
		return nil, fmt.Errorf("invalid customerId: %w", err)
	}

	docs, err := r.DebtPaymentRepo.FindByCustomer(ctx, oid)
	if err != nil {
		return nil, err
	}

	out := make([]*model.DebtPayment, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphDebtPayment(d))
	}
	return out, nil
}
