package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input model.NewExpense) (*model.Expense, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	userID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	if input.Type != "EXPENSE" && input.Type != "INCOME" {
		return nil, errors.New("type must be EXPENSE or INCOME")
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than zero")
	}

	doc := &model.ExpenseDoc{
		UserID: userID,
		Title:  input.Title,
		Type:   input.Type,
		Amount: input.Amount,
		Date:   time.Now().Unix(),
	}
	if err := r.ExpenseRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphExpense(doc), nil
}

// UpdateExpense is the resolver for the updateExpense field.
func (r *mutationResolver) UpdateExpense(ctx context.Context, id string, input model.UpdateExpense) (*model.Expense, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Title != nil {
		set["title"] = *input.Title
	}
	if input.Type != nil {
		if *input.Type != "EXPENSE" && *input.Type != "INCOME" {
			return nil, errors.New("type must be EXPENSE or INCOME")
		}
		set["type"] = *input.Type
	}
	if input.Amount != nil {
		if *input.Amount <= 0 {
			return nil, errors.New("amount must be greater than zero")
		}
		set["amount"] = *input.Amount
	}

	doc, err := r.ExpenseRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("expense not found")
	}
	return toGraphExpense(doc), nil
}

// DeleteExpense is the resolver for the deleteExpense field.
func (r *mutationResolver) DeleteExpense(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.ExpenseRepo.Delete(ctx, oid)
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context) ([]*model.Expense, error) {
	docs, err := r.ExpenseRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Expense, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphExpense(d))
	}
	return out, nil
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*model.Expense, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.ExpenseRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphExpense(doc), nil
}
