package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateImport is the resolver for the createImport field.
func (r *mutationResolver) CreateImport(ctx context.Context, input model.NewImport) (*model.Import, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	userID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	productID, err := bson.ObjectIDFromHex(input.ProductID)
	if err != nil {
		return nil, fmt.Errorf("invalid productId: %w", err)
	}

	doc := &model.ImportDoc{
		ProductID: productID,
		Quantity:  input.Quantity,
		CostPrice: input.CostPrice,
		UserID:    userID,
		Note:      input.Note,
		Date:      time.Now().Unix(),
	}
	if err := r.ImportRepo.Create(ctx, doc); err != nil {
		return nil, err
	}

	if err := r.ProductRepo.AdjustStock(ctx, productID, input.Quantity, &input.CostPrice); err != nil {
		return nil, err
	}

	return toGraphImport(doc), nil
}

// DeleteImport is the resolver for the deleteImport field.
func (r *mutationResolver) DeleteImport(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}

	imp, err := r.ImportRepo.FindByID(ctx, oid)
	if err != nil {
		return false, err
	}
	if imp == nil {
		return false, nil
	}

	if err := r.ProductRepo.AdjustStock(ctx, imp.ProductID, -imp.Quantity, nil); err != nil {
		return false, err
	}

	return r.ImportRepo.Delete(ctx, oid)
}

// Imports is the resolver for the imports field.
func (r *queryResolver) Imports(ctx context.Context) ([]*model.Import, error) {
	docs, err := r.ImportRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Import, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphImport(d))
	}
	return out, nil
}

// Import is the resolver for the import field.
func (r *queryResolver) Import(ctx context.Context, id string) (*model.Import, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.ImportRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphImport(doc), nil
}

// ImportsByProduct is the resolver for the importsByProduct field.
func (r *queryResolver) ImportsByProduct(ctx context.Context, productID string) ([]*model.Import, error) {
	oid, err := bson.ObjectIDFromHex(productID)
	if err != nil {
		return nil, fmt.Errorf("invalid productId: %w", err)
	}

	docs, err := r.ImportRepo.FindByProduct(ctx, oid)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Import, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphImport(d))
	}
	return out, nil
}
