package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	categoryID, err := bson.ObjectIDFromHex(input.CategoryID)
	if err != nil {
		return nil, fmt.Errorf("invalid categoryId: %w", err)
	}
	unitID, err := bson.ObjectIDFromHex(input.UnitID)
	if err != nil {
		return nil, fmt.Errorf("invalid unitId: %w", err)
	}

	packagingUnits, err := packagingUnitDocsFromInput(input.PackagingUnits)
	if err != nil {
		return nil, err
	}

	doc := &model.ProductDoc{
		Barcode:         input.Barcode,
		Name:            input.Name,
		ImageURL:        input.ImageURL,
		CategoryID:      categoryID,
		UnitID:          unitID,
		CostPrice:       input.CostPrice,
		RetailPrice:     input.RetailPrice,
		WholesalePrice:  input.WholesalePrice,
		WholesaleMinQty: int32(input.WholesaleMinQty),
		StockQty:        input.StockQty,
		MinStockAlert:   input.MinStockAlert,
		PackagingUnits:  packagingUnits,
	}
	if err := r.ProductRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphProduct(doc), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProduct) (*model.Product, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Barcode != nil {
		set["barcode"] = *input.Barcode
	}
	if input.Name != nil {
		set["name"] = *input.Name
	}
	if input.ImageURL != nil {
		set["imageUrl"] = *input.ImageURL
	}
	if input.CategoryID != nil {
		categoryID, err := bson.ObjectIDFromHex(*input.CategoryID)
		if err != nil {
			return nil, fmt.Errorf("invalid categoryId: %w", err)
		}
		set["categoryId"] = categoryID
	}
	if input.UnitID != nil {
		unitID, err := bson.ObjectIDFromHex(*input.UnitID)
		if err != nil {
			return nil, fmt.Errorf("invalid unitId: %w", err)
		}
		set["unitId"] = unitID
	}
	if input.CostPrice != nil {
		set["costPrice"] = *input.CostPrice
	}
	if input.RetailPrice != nil {
		set["retailPrice"] = *input.RetailPrice
	}
	if input.WholesalePrice != nil {
		set["wholesalePrice"] = *input.WholesalePrice
	}
	if input.WholesaleMinQty != nil {
		set["wholesaleMinQty"] = int32(*input.WholesaleMinQty)
	}
	if input.StockQty != nil {
		set["stockQty"] = *input.StockQty
	}
	if input.MinStockAlert != nil {
		set["minStockAlert"] = *input.MinStockAlert
	}
	if input.Status != nil {
		set["status"] = *input.Status
	}
	if input.PackagingUnits != nil {
		packagingUnits, err := packagingUnitDocsFromInput(input.PackagingUnits)
		if err != nil {
			return nil, err
		}
		set["packagingUnits"] = packagingUnits
	}

	doc, err := r.ProductRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("product not found")
	}
	return toGraphProduct(doc), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.ProductRepo.Delete(ctx, oid)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	docs, err := r.ProductRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Product, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphProduct(d))
	}
	return out, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.ProductRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphProduct(doc), nil
}
