package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateSale is the resolver for the createSale field.
func (r *mutationResolver) CreateSale(ctx context.Context, input model.NewSale) (*model.Sale, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, errors.New("not authenticated")
	}
	userID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	if len(input.Items) == 0 {
		return nil, errors.New("sale must have at least one item")
	}

	var customerID *bson.ObjectID
	if input.CustomerID != nil {
		cid, err := bson.ObjectIDFromHex(*input.CustomerID)
		if err != nil {
			return nil, fmt.Errorf("invalid customerId: %w", err)
		}
		customerID = &cid
	}

	items := make([]*model.SaleItemDoc, 0, len(input.Items))
	var total float64

	for _, itemInput := range input.Items {
		productID, err := bson.ObjectIDFromHex(itemInput.ProductID)
		if err != nil {
			return nil, fmt.Errorf("invalid productId: %w", err)
		}

		product, err := r.ProductRepo.FindByID(ctx, productID)
		if err != nil {
			return nil, err
		}
		if product == nil {
			return nil, fmt.Errorf("product %s not found", itemInput.ProductID)
		}
		if itemInput.Quantity <= 0 {
			return nil, errors.New("quantity must be greater than zero")
		}

		factor, costPrice, retailPrice, wholesalePrice, wholesaleMinQty, unitID, err := resolveSaleUnit(product, itemInput.UnitID)
		if err != nil {
			return nil, err
		}
		baseQty := itemInput.Quantity * factor

		if baseQty > product.StockQty {
			return nil, fmt.Errorf("insufficient stock for %s: have %.2f, requested %.2f", product.Name, product.StockQty, baseQty)
		}

		priceType := "RETAIL"
		unitPrice := retailPrice
		if itemInput.Quantity >= float64(wholesaleMinQty) {
			priceType = "WHOLESALE"
			unitPrice = wholesalePrice
		}

		subtotal := unitPrice * itemInput.Quantity
		total += subtotal

		items = append(items, &model.SaleItemDoc{
			ProductID: productID,
			Quantity:  itemInput.Quantity,
			CostPrice: costPrice,
			UnitPrice: unitPrice,
			PriceType: priceType,
			Subtotal:  subtotal,
			UnitID:    unitID,
			Factor:    factor,
		})
	}

	if input.Paid < 0 {
		return nil, errors.New("paid cannot be negative")
	}

	paid := input.Paid
	if paid > total {
		paid = total
	}
	debt := total - paid

	paymentStatus := "PARTIAL"
	if paid <= 0 {
		paymentStatus = "UNPAID"
	} else if debt <= 0 {
		paymentStatus = "PAID"
	}

	sale := &model.SaleDoc{
		CustomerID:    customerID,
		UserID:        userID,
		SaleDate:      time.Now().Unix(),
		Total:         total,
		Paid:          paid,
		Debt:          debt,
		PaymentStatus: paymentStatus,
		DueDate:       input.DueDate,
		PaymentMethod: input.PaymentMethod,
	}

	if err := r.SaleRepo.Create(ctx, sale, items); err != nil {
		return nil, err
	}

	for _, item := range items {
		if err := r.ProductRepo.AdjustStock(ctx, item.ProductID, -(item.Quantity * item.Factor), nil); err != nil {
			return nil, err
		}
	}

	if customerID != nil && debt > 0 {
		if err := r.CustomerRepo.AdjustDebt(ctx, *customerID, debt); err != nil {
			return nil, err
		}
	}

	return toGraphSale(sale, items), nil
}

// UpdateSale is the resolver for the updateSale field. It replaces the sale's line
// items wholesale (used for corrections/returns on a completed invoice), reverses the
// old items' effect on stock and customer debt, then reapplies fresh effects for the
// new items — paid is auto-synced to the new total (capped at it) so a corrected
// invoice is always shown as fully settled unless the new total actually exceeds what
// was paid.
func (r *mutationResolver) UpdateSale(ctx context.Context, id string, input model.UpdateSale) (*model.Sale, error) {
	if len(input.Items) == 0 {
		return nil, errors.New("sale must have at least one item")
	}

	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	sale, err := r.SaleRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if sale == nil {
		return nil, errors.New("sale not found")
	}

	oldItems, err := r.SaleRepo.ItemsBySale(ctx, oid)
	if err != nil {
		return nil, err
	}

	// Load every product referenced by either the old or new item lists up front, so
	// stock-sufficiency checks below account for both the return of old quantities and
	// the consumption of new ones at once (a product appearing in both old and new
	// items must not be double-counted). Deltas accumulate in base units throughout,
	// since old/new lines can be in different selling units (e.g. old sold as loose
	// bottles, corrected to a case) and stock is only ever tracked in the base unit.
	productDeltas := make(map[bson.ObjectID]float64)
	for _, item := range oldItems {
		oldFactor := item.Factor
		if oldFactor == 0 {
			oldFactor = 1
		}
		productDeltas[item.ProductID] += item.Quantity * oldFactor
	}

	newItems := make([]*model.SaleItemDoc, 0, len(input.Items))
	var total float64

	for _, itemInput := range input.Items {
		productID, err := bson.ObjectIDFromHex(itemInput.ProductID)
		if err != nil {
			return nil, fmt.Errorf("invalid productId: %w", err)
		}

		product, err := r.ProductRepo.FindByID(ctx, productID)
		if err != nil {
			return nil, err
		}
		if product == nil {
			return nil, fmt.Errorf("product %s not found", itemInput.ProductID)
		}
		if itemInput.Quantity <= 0 {
			return nil, errors.New("quantity must be greater than zero")
		}

		factor, costPrice, retailPrice, wholesalePrice, wholesaleMinQty, unitID, err := resolveSaleUnit(product, itemInput.UnitID)
		if err != nil {
			return nil, err
		}

		priceType := "RETAIL"
		unitPrice := retailPrice
		if itemInput.Quantity >= float64(wholesaleMinQty) {
			priceType = "WHOLESALE"
			unitPrice = wholesalePrice
		}

		subtotal := unitPrice * itemInput.Quantity
		total += subtotal

		newItems = append(newItems, &model.SaleItemDoc{
			ProductID: productID,
			Quantity:  itemInput.Quantity,
			CostPrice: costPrice,
			UnitPrice: unitPrice,
			PriceType: priceType,
			Subtotal:  subtotal,
			UnitID:    unitID,
			Factor:    factor,
		})

		productDeltas[productID] -= itemInput.Quantity * factor
	}

	// Stock sufficiency check: a positive delta means stock would be returned (fine),
	// a negative delta means stock would be consumed beyond what's on hand.
	for productID, delta := range productDeltas {
		if delta >= 0 {
			continue
		}
		product, err := r.ProductRepo.FindByID(ctx, productID)
		if err != nil {
			return nil, err
		}
		if product != nil && product.StockQty+delta < 0 {
			return nil, fmt.Errorf("insufficient stock for %s: have %.2f, short by %.2f", product.Name, product.StockQty, -(product.StockQty + delta))
		}
	}

	paid := sale.Paid
	if paid > total {
		paid = total
	}
	debt := total - paid

	paymentStatus := "PARTIAL"
	if paid <= 0 {
		paymentStatus = "UNPAID"
	} else if debt <= 0 {
		paymentStatus = "PAID"
	}

	if err := r.SaleRepo.ReplaceItems(ctx, oid, newItems, total, paid, debt, paymentStatus); err != nil {
		return nil, err
	}

	for productID, delta := range productDeltas {
		if delta == 0 {
			continue
		}
		if err := r.ProductRepo.AdjustStock(ctx, productID, delta, nil); err != nil {
			return nil, err
		}
	}

	if sale.CustomerID != nil {
		debtDelta := debt - sale.Debt
		if debtDelta != 0 {
			if err := r.CustomerRepo.AdjustDebt(ctx, *sale.CustomerID, debtDelta); err != nil {
				return nil, err
			}
		}
	}

	sale.Total = total
	sale.Paid = paid
	sale.Debt = debt
	sale.PaymentStatus = paymentStatus

	return toGraphSale(sale, newItems), nil
}

// DeleteSale is the resolver for the deleteSale field.
func (r *mutationResolver) DeleteSale(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}

	sale, err := r.SaleRepo.FindByID(ctx, oid)
	if err != nil {
		return false, err
	}
	if sale == nil {
		return false, nil
	}

	items, err := r.SaleRepo.ItemsBySale(ctx, oid)
	if err != nil {
		return false, err
	}

	for _, item := range items {
		factor := item.Factor
		if factor == 0 {
			factor = 1
		}
		if err := r.ProductRepo.AdjustStock(ctx, item.ProductID, item.Quantity*factor, nil); err != nil {
			return false, err
		}
	}

	if sale.CustomerID != nil && sale.Debt > 0 {
		if err := r.CustomerRepo.AdjustDebt(ctx, *sale.CustomerID, -sale.Debt); err != nil {
			return false, err
		}
	}

	return r.SaleRepo.Delete(ctx, oid)
}

// Sales is the resolver for the sales field.
func (r *queryResolver) Sales(ctx context.Context) ([]*model.Sale, error) {
	docs, err := r.SaleRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Sale, 0, len(docs))
	for _, d := range docs {
		items, err := r.SaleRepo.ItemsBySale(ctx, d.ID)
		if err != nil {
			return nil, err
		}
		out = append(out, toGraphSale(d, items))
	}
	return out, nil
}

// Sale is the resolver for the sale field.
func (r *queryResolver) Sale(ctx context.Context, id string) (*model.Sale, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.SaleRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}

	items, err := r.SaleRepo.ItemsBySale(ctx, oid)
	if err != nil {
		return nil, err
	}
	return toGraphSale(doc, items), nil
}

// SalesByCustomer is the resolver for the salesByCustomer field.
func (r *queryResolver) SalesByCustomer(ctx context.Context, customerID string) ([]*model.Sale, error) {
	oid, err := bson.ObjectIDFromHex(customerID)
	if err != nil {
		return nil, fmt.Errorf("invalid customerId: %w", err)
	}

	docs, err := r.SaleRepo.FindByCustomer(ctx, oid)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Sale, 0, len(docs))
	for _, d := range docs {
		items, err := r.SaleRepo.ItemsBySale(ctx, d.ID)
		if err != nil {
			return nil, err
		}
		out = append(out, toGraphSale(d, items))
	}
	return out, nil
}
