package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
)

// CreateScanSession is the resolver for the createScanSession field.
func (r *mutationResolver) CreateScanSession(ctx context.Context) (string, error) {
	return r.ScanBroker.Create(), nil
}

// SubmitScan is the resolver for the submitScan field.
func (r *mutationResolver) SubmitScan(ctx context.Context, sessionID string, code string) (bool, error) {
	if code == "" {
		return false, errors.New("code must not be empty")
	}
	ok := r.ScanBroker.Publish(sessionID, code)
	if !ok {
		return false, errors.New("scan session not found or expired")
	}
	return true, nil
}

// ScanReceived is the resolver for the scanReceived field.
func (r *subscriptionResolver) ScanReceived(ctx context.Context, sessionID string) (<-chan string, error) {
	ch, cleanup, ok := r.ScanBroker.Subscribe(sessionID)
	if !ok {
		return nil, errors.New("scan session not found or expired")
	}

	go func() {
		<-ctx.Done()
		cleanup()
	}()

	return ch, nil
}
