package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// CreateUnit is the resolver for the createUnit field.
func (r *mutationResolver) CreateUnit(ctx context.Context, input model.NewUnit) (*model.Unit, error) {
	doc := &model.UnitDoc{Name: input.Name}
	if err := r.UnitRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphUnit(doc), nil
}

// UpdateUnit is the resolver for the updateUnit field.
func (r *mutationResolver) UpdateUnit(ctx context.Context, id string, input model.UpdateUnit) (*model.Unit, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Name != nil {
		set["name"] = *input.Name
	}

	doc, err := r.UnitRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("unit not found")
	}
	return toGraphUnit(doc), nil
}

// DeleteUnit is the resolver for the deleteUnit field.
func (r *mutationResolver) DeleteUnit(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.UnitRepo.Delete(ctx, oid)
}

// Units is the resolver for the units field.
func (r *queryResolver) Units(ctx context.Context) ([]*model.Unit, error) {
	docs, err := r.UnitRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Unit, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphUnit(d))
	}
	return out, nil
}

// Unit is the resolver for the unit field.
func (r *queryResolver) Unit(ctx context.Context, id string) (*model.Unit, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.UnitRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphUnit(doc), nil
}
