package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	doc, err := r.UserRepo.FindByUsername(ctx, username)
	if err != nil {
		return nil, err
	}
	if doc == nil || !auth.CheckPassword(doc.PasswordHash, password) {
		return nil, errors.New("invalid username or password")
	}
	if doc.Status != "ACTIVE" {
		return nil, errors.New("user is not active")
	}

	token, err := r.JWT.Generate(doc.ID.Hex(), doc.Role)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphUser(doc),
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	hash, err := auth.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}

	doc := &model.UserDoc{
		Username:     input.Username,
		PasswordHash: hash,
		Role:         input.Role,
		FirstName:    input.FirstName,
		LastName:     input.LastName,
		Phone:        input.Phone,
		Status:       "ACTIVE",
	}
	if err := r.UserRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphUser(doc), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUser) (*model.User, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Role != nil {
		set["role"] = *input.Role
	}
	if input.FirstName != nil {
		set["firstName"] = *input.FirstName
	}
	if input.LastName != nil {
		set["lastName"] = *input.LastName
	}
	if input.Phone != nil {
		set["phone"] = *input.Phone
	}
	if input.Status != nil {
		set["status"] = *input.Status
	}

	doc, err := r.UserRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("user not found")
	}
	return toGraphUser(doc), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.UserRepo.Delete(ctx, oid)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, errors.New("not authenticated")
	}

	oid, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	doc, err := r.UserRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("user not found")
	}
	return toGraphUser(doc), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	if _, ok := auth.ClaimsFromContext(ctx); !ok {
		return nil, errors.New("not authenticated")
	}

	docs, err := r.UserRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.User, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphUser(d))
	}
	return out, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, ok := auth.ClaimsFromContext(ctx); !ok {
		return nil, errors.New("not authenticated")
	}

	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.UserRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphUser(doc), nil
}
