package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"agriculture-api/graph/model"
	"agriculture-api/internal/auth"
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// issueTokenPair generates a fresh access token + refresh token for a user,
// persisting the refresh token's hash so it can be looked up and rotated later.
func (r *mutationResolver) issueTokenPair(ctx context.Context, doc *model.UserDoc) (*model.AuthPayload, error) {
	accessToken, err := r.JWT.Generate(doc.ID.Hex(), doc.Role)
	if err != nil {
		return nil, err
	}

	refreshSecret, err := auth.NewRefreshTokenSecret()
	if err != nil {
		return nil, err
	}

	if err := r.RefreshTokenRepo.Create(ctx, &model.RefreshTokenDoc{
		UserID:    doc.ID,
		TokenHash: auth.HashRefreshToken(refreshSecret),
		ExpiresAt: time.Now().Add(r.RefreshTokenTTL),
	}); err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token:        accessToken,
		RefreshToken: refreshSecret,
		User:         toGraphUser(doc),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	doc, err := r.UserRepo.FindByUsername(ctx, username)
	if err != nil {
		return nil, err
	}
	if doc == nil || !auth.CheckPassword(doc.PasswordHash, password) {
		return nil, errors.New("invalid username or password")
	}
	if doc.Status != "ACTIVE" {
		return nil, errors.New("user is not active")
	}

	return r.issueTokenPair(ctx, doc)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	tokenHash := auth.HashRefreshToken(refreshToken)

	existing, err := r.RefreshTokenRepo.FindByHash(ctx, tokenHash)
	if err != nil {
		return nil, err
	}
	if existing == nil || existing.ExpiresAt.Before(time.Now()) {
		return nil, errors.New("refresh token is invalid or expired")
	}

	doc, err := r.UserRepo.FindByID(ctx, existing.UserID)
	if err != nil {
		return nil, err
	}
	if doc == nil || doc.Status != "ACTIVE" {
		return nil, errors.New("user is not active")
	}

	// Rotate: the old refresh token is single-use. Issuing a new one with a
	// fresh 7-day expiry on every refresh is what gives the sliding-window
	// behavior — as long as the app is opened at least once within 7 days,
	// the session keeps extending itself instead of expiring.
	if err := r.RefreshTokenRepo.DeleteByHash(ctx, tokenHash); err != nil {
		return nil, err
	}

	return r.issueTokenPair(ctx, doc)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	if err := r.RefreshTokenRepo.DeleteByHash(ctx, auth.HashRefreshToken(refreshToken)); err != nil {
		return false, err
	}
	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	hash, err := auth.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}

	doc := &model.UserDoc{
		Username:     input.Username,
		PasswordHash: hash,
		Role:         input.Role,
		FirstName:    input.FirstName,
		LastName:     input.LastName,
		Phone:        input.Phone,
		Status:       "ACTIVE",
	}
	if err := r.UserRepo.Create(ctx, doc); err != nil {
		return nil, err
	}
	return toGraphUser(doc), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUser) (*model.User, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}

	set := bson.M{}
	if input.Role != nil {
		set["role"] = *input.Role
	}
	if input.FirstName != nil {
		set["firstName"] = *input.FirstName
	}
	if input.LastName != nil {
		set["lastName"] = *input.LastName
	}
	if input.Phone != nil {
		set["phone"] = *input.Phone
	}
	if input.Status != nil {
		set["status"] = *input.Status
	}

	doc, err := r.UserRepo.Update(ctx, oid, set)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("user not found")
	}
	return toGraphUser(doc), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid id: %w", err)
	}
	return r.UserRepo.Delete(ctx, oid)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}

	oid, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, err
	}

	doc, err := r.UserRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, errors.New("user not found")
	}
	return toGraphUser(doc), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	if _, ok := auth.ClaimsFromContext(ctx); !ok {
		return nil, auth.ErrUnauthenticated
	}

	docs, err := r.UserRepo.FindAll(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.User, 0, len(docs))
	for _, d := range docs {
		out = append(out, toGraphUser(d))
	}
	return out, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, ok := auth.ClaimsFromContext(ctx); !ok {
		return nil, auth.ErrUnauthenticated
	}

	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	doc, err := r.UserRepo.FindByID(ctx, oid)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return toGraphUser(doc), nil
}
