// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Customer struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Phone   string  `json:"phone"`
	Address *string `json:"address,omitempty"`
	Debt    float64 `json:"debt"`
	Status  string  `json:"status"`
}

type DamagedProduct struct {
	ID        string  `json:"id"`
	ProductID string  `json:"productId"`
	UserID    string  `json:"userId"`
	Quantity  float64 `json:"quantity"`
	CostPrice float64 `json:"costPrice"`
	Reason    string  `json:"reason"`
	Note      *string `json:"note,omitempty"`
	Date      string  `json:"date"`
}

type DebtPayment struct {
	ID          string  `json:"id"`
	SaleID      string  `json:"saleId"`
	CustomerID  string  `json:"customerId"`
	UserID      string  `json:"userId"`
	AmountPaid  float64 `json:"amountPaid"`
	PaymentDate string  `json:"paymentDate"`
	Note        *string `json:"note,omitempty"`
}

type Expense struct {
	ID     string  `json:"id"`
	UserID string  `json:"userId"`
	Title  string  `json:"title"`
	Type   string  `json:"type"`
	Amount float64 `json:"amount"`
	Date   string  `json:"date"`
}

type Import struct {
	ID        string  `json:"id"`
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	CostPrice float64 `json:"costPrice"`
	UserID    string  `json:"userId"`
	Note      *string `json:"note,omitempty"`
	Date      string  `json:"date"`
}

type Mutation struct {
}

type NewCategory struct {
	Name string `json:"name"`
}

type NewCustomer struct {
	Name    string  `json:"name"`
	Phone   string  `json:"phone"`
	Address *string `json:"address,omitempty"`
}

type NewDamagedProduct struct {
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	Reason    string  `json:"reason"`
	Note      *string `json:"note,omitempty"`
}

type NewDebtPayment struct {
	SaleID     string  `json:"saleId"`
	AmountPaid float64 `json:"amountPaid"`
	Note       *string `json:"note,omitempty"`
}

type NewExpense struct {
	Title  string  `json:"title"`
	Type   string  `json:"type"`
	Amount float64 `json:"amount"`
}

type NewImport struct {
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	CostPrice float64 `json:"costPrice"`
	Note      *string `json:"note,omitempty"`
}

type NewProduct struct {
	Barcode         *string               `json:"barcode,omitempty"`
	Name            string                `json:"name"`
	ImageURL        *string               `json:"imageUrl,omitempty"`
	CategoryID      string                `json:"categoryId"`
	UnitID          string                `json:"unitId"`
	CostPrice       float64               `json:"costPrice"`
	RetailPrice     float64               `json:"retailPrice"`
	WholesalePrice  float64               `json:"wholesalePrice"`
	WholesaleMinQty int                   `json:"wholesaleMinQty"`
	StockQty        float64               `json:"stockQty"`
	MinStockAlert   float64               `json:"minStockAlert"`
	PackagingUnits  []*PackagingUnitInput `json:"packagingUnits,omitempty"`
}

type NewSale struct {
	CustomerID    *string        `json:"customerId,omitempty"`
	Items         []*NewSaleItem `json:"items"`
	Paid          float64        `json:"paid"`
	Discount      *float64       `json:"discount,omitempty"`
	DueDate       *string        `json:"dueDate,omitempty"`
	PaymentMethod *string        `json:"paymentMethod,omitempty"`
}

type NewSaleItem struct {
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	UnitID    *string `json:"unitId,omitempty"`
}

type NewUnit struct {
	Name string `json:"name"`
}

type NewUser struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Role      string `json:"role"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Phone     string `json:"phone"`
}

type PackagingUnit struct {
	UnitID          string  `json:"unitId"`
	Factor          float64 `json:"factor"`
	CostPrice       float64 `json:"costPrice"`
	RetailPrice     float64 `json:"retailPrice"`
	WholesalePrice  float64 `json:"wholesalePrice"`
	WholesaleMinQty int     `json:"wholesaleMinQty"`
}

type PackagingUnitInput struct {
	UnitID          string  `json:"unitId"`
	Factor          float64 `json:"factor"`
	CostPrice       float64 `json:"costPrice"`
	RetailPrice     float64 `json:"retailPrice"`
	WholesalePrice  float64 `json:"wholesalePrice"`
	WholesaleMinQty int     `json:"wholesaleMinQty"`
}

type Product struct {
	ID              string           `json:"id"`
	Barcode         *string          `json:"barcode,omitempty"`
	Name            string           `json:"name"`
	ImageURL        *string          `json:"imageUrl,omitempty"`
	CategoryID      string           `json:"categoryId"`
	UnitID          string           `json:"unitId"`
	CostPrice       float64          `json:"costPrice"`
	RetailPrice     float64          `json:"retailPrice"`
	WholesalePrice  float64          `json:"wholesalePrice"`
	WholesaleMinQty int              `json:"wholesaleMinQty"`
	StockQty        float64          `json:"stockQty"`
	MinStockAlert   float64          `json:"minStockAlert"`
	Status          string           `json:"status"`
	PackagingUnits  []*PackagingUnit `json:"packagingUnits"`
}

type Query struct {
}

type Sale struct {
	ID            string      `json:"id"`
	Code          string      `json:"code"`
	CustomerID    *string     `json:"customerId,omitempty"`
	UserID        string      `json:"userId"`
	SaleDate      string      `json:"saleDate"`
	Subtotal      float64     `json:"subtotal"`
	Discount      float64     `json:"discount"`
	Total         float64     `json:"total"`
	Paid          float64     `json:"paid"`
	Debt          float64     `json:"debt"`
	PaymentStatus string      `json:"paymentStatus"`
	DueDate       *string     `json:"dueDate,omitempty"`
	PaymentMethod *string     `json:"paymentMethod,omitempty"`
	Items         []*SaleItem `json:"items"`
}

type SaleItem struct {
	ID        string  `json:"id"`
	SaleID    string  `json:"saleId"`
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	CostPrice float64 `json:"costPrice"`
	UnitPrice float64 `json:"unitPrice"`
	PriceType string  `json:"priceType"`
	Subtotal  float64 `json:"subtotal"`
	UnitID    *string `json:"unitId,omitempty"`
	Factor    float64 `json:"factor"`
}

type Subscription struct {
}

type Unit struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateCategory struct {
	Name *string `json:"name,omitempty"`
}

type UpdateCustomer struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
	Status  *string `json:"status,omitempty"`
}

type UpdateExpense struct {
	Title  *string  `json:"title,omitempty"`
	Type   *string  `json:"type,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
}

type UpdateProduct struct {
	Barcode         *string               `json:"barcode,omitempty"`
	Name            *string               `json:"name,omitempty"`
	ImageURL        *string               `json:"imageUrl,omitempty"`
	CategoryID      *string               `json:"categoryId,omitempty"`
	UnitID          *string               `json:"unitId,omitempty"`
	CostPrice       *float64              `json:"costPrice,omitempty"`
	RetailPrice     *float64              `json:"retailPrice,omitempty"`
	WholesalePrice  *float64              `json:"wholesalePrice,omitempty"`
	WholesaleMinQty *int                  `json:"wholesaleMinQty,omitempty"`
	StockQty        *float64              `json:"stockQty,omitempty"`
	MinStockAlert   *float64              `json:"minStockAlert,omitempty"`
	Status          *string               `json:"status,omitempty"`
	PackagingUnits  []*PackagingUnitInput `json:"packagingUnits,omitempty"`
}

type UpdateSale struct {
	Items    []*UpdateSaleItem `json:"items"`
	Discount *float64          `json:"discount,omitempty"`
}

type UpdateSaleItem struct {
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
	UnitID    *string `json:"unitId,omitempty"`
}

type UpdateUnit struct {
	Name *string `json:"name,omitempty"`
}

type UpdateUser struct {
	Role      *string `json:"role,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Status    *string `json:"status,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Phone     string `json:"phone"`
	Status    string `json:"status"`
}
